services:
    wubook_api.client:
        class: Kamwoz\WubookAPIBundle\Client
        arguments:
            - '@wubook_api.token_provider'
            - '%wubook_api.url%'
        public: true
    wubook_api.base_handler:
        class: Kamwoz\WubookAPIBundle\Handler\BaseHandler
    wubook_api.token_handler:
        class: Kamwoz\WubookAPIBundle\Handler\TokenHandler
        parent: "wubook_api.base_handler"
        public: true
    wubook_api.booking_handler:
        class: Kamwoz\WubookAPIBundle\Handler\BookingHandler
        arguments: ["%wubook_api.reservation_model%"]
        public: true
        parent: "wubook_api.base_handler"
    wubook_api.token_provider:
        class: Kamwoz\WubookAPIBundle\Utils\YamlTokenProvider
        arguments: ["%kernel.cache_dir%/wubook_api_token.yml"]
    wubook_api.room_handler:
        class: Kamwoz\WubookAPIBundle\Handler\RoomHandler
        arguments: ["%wubook_api.room_model%"]
        public: true
        parent: "wubook_api.base_handler"
    wubook_api.avaiability_handler:
        class: Kamwoz\WubookAPIBundle\Handler\AvailabilityHandler
        public: true
        parent: "wubook_api.base_handler"