services:
    wubook_api.client:
        class: Kamwoz\WubookAPIBundle\Client
        arguments:
            - @wubook_api.token_provider
            - %wubook_api.client_username%
            - %wubook_api.client_password%
            - %wubook_api.provider_key%
            - %wubook_api.url%
            - %wubook_api.property_id%
        public: false
    wubook_api.base_handler:
        class: Kamwoz\WubookAPIBundle\Handler\BaseHandler
    wubook_api.token_handler:
        class: Kamwoz\WubookAPIBundle\Handler\TokenHandler
        parent: "wubook_api.base_handler"
        public: true
    wubook_api.reservation_handler:
        class: Kamwoz\WubookAPIBundle\Handler\ReservationHandler
        public: true
        parent: "wubook_api.base_handler"
    wubook_api.token_provider:
        class: Kamwoz\WubookAPIBundle\Utils\YamlTokenProvider
        arguments: ["%kernel.cache_dir%/wubook_api_token.yml"]
    wubook_api.room_handler:
        class: Kamwoz\WubookAPIBundle\Handler\RoomHandler
        public: true
        parent: "wubook_api.base_handler"